trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'
  resourceGroup: 'talesandtale-europe-rg'
  appName: 'talesatale-wa-eu'
  planName: 'talesatale-as-eu'


stages:
- stage: Build
  jobs:
  - job: Build
    steps:
    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        version: '8.x'
        installationPath: $(Agent.ToolsDirectory)/dotnet

    - task: DotNetCoreCLI@2
      inputs:
        command: 'restore'
        projects: '**/*.csproj'

    - task: DotNetCoreCLI@2
      inputs:
        command: 'build'
        projects: '**/*.csproj'
        arguments: '--configuration $(buildConfiguration)'

    - task: DotNetCoreCLI@2
      inputs:
        command: 'test'
        projects: '**/*.csproj'
        arguments: '--configuration $(buildConfiguration) --no-build'

    - task: DotNetCoreCLI@2
      inputs:
        command: 'publish'
        projects: '**/*.csproj'
        arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'

    - publish: $(Build.ArtifactStagingDirectory)
      artifact: drop

- stage: Create_Ressource
  displayName: Creating azure web resource for deploypment
  dependsOn: Build
  jobs:
  - job: AppService
    displayName: Create azure app service
    steps:
      - task: AzureCLI@2
        inputs:
          azureSubscription: 'Visual Studio Professional Subscription(0f7a3b62-c1a4-4aa9-97c3-3bf5f497b5ab)'
          scriptType: 'batch'
          scriptLocation: 'inlineScript'
          inlineScript: |

            # Create App Service Plan if it doesn't exist
            az appservice plan show --name $(resourceGroup) --resource-group $(resourceGroup) > /dev/null 2>&1 || \
            az appservice plan create --name $(planName) --resource-group $(resourceGroup) --sku B1
            
            # Create App Service if it doesn't exist
            az webapp show --name $(appName) --resource-group $(resourceGroup) > /dev/null 2>&1 || \
            az webapp create --name $(appName) --resource-group $(resourceGroup) --plan $(planName) --runtime "DOTNETCORE|8.0"


- stage: Deploy
  dependsOn: Create_Ressource
  jobs:
  - deployment: DeployWebApp
    environment: 'production'
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: drop

          - task: UseDotNet@2
            inputs:
              packageType: 'sdk'
              version: '8.x'
              installationPath: $(Agent.ToolsDirectory)/dotnet

          - task: AzureWebApp@1
            inputs:
              azureSubscription: 'Visual Studio Professional Subscription(0f7a3b62-c1a4-4aa9-97c3-3bf5f497b5ab)'
              appType: 'webApp'
              appName: 'StoryTellingApi'
              resourceGroupName: 'talesandtale-europe-rg'
              package: '$(Pipeline.Workspace)/drop'
