stages:
- stage: Create_Ressource
  displayName: Creating azure web resource for deploypment
  dependsOn: Build
  jobs:
  - job: AppService
    displayName: Create azure app service
    steps:
      - task: AzureCLI@2
        inputs:
          azureSubscription: 'Visual Studio Professional Subscription(0f7a3b62-c1a4-4aa9-97c3-3bf5f497b5ab)'
          scriptType: 'batch'
          scriptLocation: 'inlineScript'
          inlineScript: |

            # Create App Service Plan if it doesn't exist
            az appservice plan show --name $(resourceGroup) --resource-group $(resourceGroup) > /dev/null 2>&1 || \
            az appservice plan create --name $(planName) --resource-group $(resourceGroup) --sku B1
            
            # Create App Service if it doesn't exist
            az webapp show --name $(appName) --resource-group $(resourceGroup) > /dev/null 2>&1 || \
            az webapp create --name $(appName) -g $(resourceGroup) --plan $(planName) --runtime dotnet:8
