parameters:
  - name: stage
    type: string
  - name: application
    type: string
  - name: apiProjectLocation
    type: string
  - name: dbProjectLocation
    type: string
  - name: buildConfig
    type: string

stages:
  - stage: Build
    jobs:
    - job: Build
      steps:
      - task: UseDotNet@2
        inputs:
          packageType: 'sdk'
          version: '8.x'
          installationPath: $(Agent.ToolsDirectory)/dotnet

      - task: DotNetCoreCLI@2
        inputs:
          command: 'restore'
          projects: '**/*.csproj'

      - task: DotNetCoreCLI@2
        inputs:
          command: 'build'
          projects: '**/*.csproj'
          arguments: '--configuration $(buildConfig)'

      - task: DotNetCoreCLI@2
        inputs:
          command: 'custom'
          custom: 'tool'
          arguments: 'update --global dotnet-ef'
        displayName: 'Intall Dotnet Ef Tools'

      - task: DotNetCoreCLI@2
        inputs:
          command: 'custom'
          custom: 'ef'
          arguments: 'migrations script --no-build --idempotent --context ApplicationDbContext --configuration $(buildConfig) --project $(databaseProjectLocation)/Infrastructure.csproj --startup-project $(mainProjectLocation)/StoryTellingApi.csproj --output  $(Build.ArtifactStagingDirectory)/Migrations/storyTellScript.sql'
        displayName: 'Generate Migration Script' 

      - task: DotNetCoreCLI@2
        inputs:
          command: 'publish'
          projects: '**/*.csproj'
          arguments: '--configuration $(buildConfig) --output $(Build.ArtifactStagingDirectory)'
          zipAfterPublish: true

      - publish: $(Build.ArtifactStagingDirectory)
        artifact: drop